### ISSUE TITLE
Add a door demo

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/demo-things#14]
- [ ] Exposes a [DoorSensor](https://webthings.io/schemas/#DoorSensor) and a [Lock](https://webthings.io/schemas/#Lock)
- [ ] Errors if the Door is open according to the sensor and any Lock Action is requested
- [ ] Takes a configuration file that changes the state of the door over `ticks` (Open, Closed, Locked) simulating access.
- [ ] Hot-reloads the configuration file.

**Comment by dodomorandi** [comment]
I think that [`LockedProperty`](https://webthings.io/schemas/#LockedProperty) is a bit underspecified:
- `jammed` variant should be stateful: a `locked jammed` lock is **very different** from an `unlocked jammed` lock.
- `unknown` variant is totally meaningless, it does not describe a valid state and the result of [lock](https://webthings.io/schemas/#LockAction) and  [unlock](https://webthings.io/schemas/#UnlockAction) actions is not specified.

I am going to omit the `unknown' variant, and I am leaving the `jammed` variant stateless, it's ok for our demo (but I don't thing that can correctly represent real cases).
