### ISSUE TITLE
Need `base` member or absolute URLs in `href` members

### ISSUE THREAD

**Issue by benfrancis** [sifis-home/demo-things#23]
When I try to add the lamp Thing to my WoT Consumer, it complains that the Thing Description is not valid because the values of `href` are not valid URLs.

The reason for this is that the values of `href` are paths, not full URLs, and there's no `base` member with a root URL to resolve them against.

I assume that you intend for the paths to be relative to the root of the domain, but once a Thing Description is added to a directory there is no way for a Consumer to know what the source origin was. It's therefore not possible for a Consumer to fetch any of the URLs provided in Forms.

I think you need to either:
- Add a `base` member which provides the root URL against which `href` members should be resolved
- Make `href` members absolute URLs

Note that this requires that the server knows the host from which the Thing Description is being served, which will not always be localhost.

**Comment by lu-zero** [comment]
For the demo-things I can add a `--base` override and use the mdns name as default base in general.
